name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Deploy to gh-pages
        run: |
          # Copy main site files to gh-pages root
          cp index.html gh-pages/
          cp styles.css gh-pages/
          cp script.js gh-pages/
          
          # Ensure .nojekyll exists for proper GitHub Pages serving
          touch gh-pages/.nojekyll
          
          # Commit and push
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html styles.css script.js .nojekyll
          
          if git diff --staged --quiet; then
            echo "No changes to deploy"
          else
            git commit -m "Deploy main branch to GitHub Pages"
            git push
            echo "? Deployed to GitHub Pages"
          fi

